import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { headers } from "next/headers"; 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const isAdminPanel = headersList.get("x-is-admin-panel") === "true";

  return (
    <html lang="en">
      <body dir="rtl">
        {!isAdminPanel && <Navbar />}
        {children}
        {!isAdminPanel && <Footer />}
      </body>
    </html>
  );
}